server:
  port: ${SERVICE_HOST}
  servlet:
    context-path: /identity

spring:
  datasource:
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: ErpCdcDBCP
        jdbc-url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        auto-commit: true
        connection-timeout: 30000
        idle-timeout: 60000
        max-lifetime: 180000
        minimum-idle: 50
        maximum-pool-size: 500
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
  jpa:
    show-sql: true
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION} # time hết hạn token (giây)
  refreshable-duration: ${JWT_REFRESHABLE_DURATION} # time có thể refresh token kể từ lúc tạo (giây)
base-url:
  user-profile: ${BASE_URL_USER_PROFILE}