server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: 'jdbc:mysql://localhost:33309/lab_hieugn'
    username: hieugn
    password: 123456
  jpa:
    show-sql: true